### ISSUE TITLE
Refactor TcpServer to accept a configuration object

### ISSUE THREAD

**Issue by LDSpits** [Deefoozy/MultiThreadedWebSocketServer#12]
Currently, the ``TcpServer`` has configuration for the server (ports, ip adresses) hardcoded in the server. The server class is also static and should be a non static class to improve usability and we might want to look into configuration files for the project to make it easier to configure default values.

1. - [ ] Create a configuration object containing IP & port with defaults.
2. - [ ] Make the TcpServer configurable throught the consturctor with said object.

**Comment by frosch95** [comment]
Do you really want to start multiple servers inside one application or do you want to start multiple applications with different configurations?

IMHO the second one is the easier way to handle it, because with multiple servers inside one application you have to put the server loop into a thread (e.g. Task.Run()) to run more than one server. Otherwise the first server blocks the main thread with the loop.

This will end in some real complex async problems as the application has to run as long as at least one server is running. If you want to implement this, I suggest to have a look at the async await concept https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/
and use the Async methods on the .net core objects.

And if you want make multiple servers running in one application, I suggest to configure the server in the constructor as this is data should be unchangeable for the server. Otherwise you can call the Start method with different settings, while the server is still running with the old settings.

my 2 cents :-)

regards 
Andi

**Comment by Deefoozy** [comment]
I think it might be a better idea to just have one server (listener) running that handles traffic, I think this would be a good addition to the 0.2 "release", I still want to hear @LDSpits explain his point though!
Passing a configuration object and renaming the initiate function to start are both things that should happen. However i do not see the point in inheriting a tcpserver class.

Thanks for your opinion btw @frosch95 !

**Comment by LDSpits** [comment]
In hindsight, the example I gave was not a good one (multiple servers in one application). but I still feel that we should not have the server class as a static. If anything, it will give us control over when to instantiate the server. instead of always creating it no matter the situation.

**Comment by frosch95** [comment]
I totally agree to make the server not static. Static reduces testability.

How about the following steps?

1. making the TcpServer configurable through the constructor
2. use the args array in Programs.cs to receive IP and Port, but also provide defaults
3. and maybe add Configuration API to the app https://garywoodfine.com/configuration-api-net-core-console-application/

**Comment by Deefoozy** [comment]
I think it's a good idea to have this issue ready for 0.2, I think it should contain the points mentioned by @frosch95 . I think it might be a good idea to edit the issue to have a checklist with these 3 items and remove the debated tag if there are no objections.

**Comment by LDSpits** [comment]
No objections here, the only thing I have to look into is point 3. But the rest I totally agree with.
